ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<int:i>',views.addtocart,name='addtocart'),
    path('cart',views.cart_view,name='cart'),
    path('cartremove/<int:i>', views.cart_remove, name='cartremove'),
    path('cartdelete/<int:i>', views.cart_delete, name='cartdelete'),
    path('orderform',views.order_form,name='orderform'),
    path('status/<u>',views.payment_status,name='status'),
    path('orderview',views.order_view,name='orderview'),
    path('addcategories',views.add_categories,name="addcategories"),
    path('addproducts',views.add_products,name="addproducts")
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include


from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('search',views.search_products,name='search')
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('',views.categories,name='categories'),
    path('products/<int:p>',views.Products,name='products'),
    path('detail/<int:p>',views.details,name='details'),
    path('register', views.Register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('stock/<int:k>',views.add_stock,name="stock"),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quality = models.IntegerField(default=1)
    date_added = models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.quality*self.product.price



class Order_details(models.Model):
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    user= models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone_no=models.BigIntegerField()
    pin=models.IntegerField()


    order_id=models.CharField(max_length=20,blank=True)
    ordered_date=models.DateTimeField(auto_now_add=True)

    payment_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")

class Payment(models.Model):
    name=models.CharField(max_length=30)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30,blank=True)
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from shop.models import Categories
from cart.models import Cart
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
import razorpay
from cart.models import Payment
from cart.models import Order_details
from django.views.decorators.csrf import csrf_exempt

@login_required
def addtocart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(product=p,user=u)
        if(p.stock>0):
              c.quality+=1
              c.save()
              p.stock-=1
              p.save()
    except:
        if(p.stock>0):
              c=Cart.objects.create(product=p,user=u,quality=1)
              c.save()
              p.stock-=1
              p.save()

    return redirect('cart:cart')

def cart_view(request):
     u = request.user
     c = Cart.objects.filter(user=u)
     total = 0
     for i in c:
            total += i.quality*i.product.price
            context={'cart':c, 'total': total}
     return render(request, 'cart.html',context)

@login_required
def cart_remove(request,i):

    p=Product.objects.get(id=i)
    u=request.user

    try:
        c=Cart.objects.get(product=p,user=u)
        if(c.quality>1):
            c.quality-=1
            c.save()
            p.stock+=1
            p.save()
        else:
            c.delete()
            p.stock += 1
            p.save()
    except:
        pass

    return redirect('cart:cart')

@login_required
def cart_delete(request,i):

    p=Product.objects.get(id=i)
    u=request.user

    try:
        c = Cart.objects.get(product=p, user=u)
        c.delete()
        p.stock += c.quantity
        p.save()
    except:
        pass

    return redirect('cart:cart')

@login_required
def order_form(request):
    if(request.method=="POST"):
        address=request.POST['a']
        phone=request.POST['p']
        pin=request.POST['pi']
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.quality*i.product.price
        total1=int(total*100)
        print(total)
        client=razorpay.Client(auth=('rzp_test_37h3t9ZIGC5fDa','qfxNvjz8OoxUOx10xeltJIGO'))
        response_payment=client.order.create(dict(amount=total1,currency="INR"))
        print(response_payment)
        order_id=response_payment['id']
        status=response_payment['status']

        if(status=="created"):
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:
                o = Order_details.objects.create(products=i.product, user=u, no_of_items=i.quality, address=address, pin=pin,phone_no=phone, order_id=order_id)
                o.save()
            response_payment['name'] = u.username
        context = {'payment': response_payment}
        return render(request, 'payment.html',context)

    return render(request,'orderform.html')

@csrf_exempt
def payment_status(request,u):
  u= User.objects.get(username=u)
  if not request.user.is_authenticated:
    login(request,u)

  if(request.method=="POST"):
    response=request.POST
    print(response)
    param_dict={
         'razorpay_order_id':response['razorpay_order_id'],
         'razorpay_payment_id': response['razorpay_payment_id'],
         'razorpay_signature': response['razorpay_signature'],
      }#to check the authentication of rayzorpay signature
    client=razorpay.Client(auth=('rzp_test_37h3t9ZIGC5fDa','qfxNvjz8OoxUOx10xeltJIGO'))
    print(client)
    try:
        status=client.utility.verify_payment_signature(param_dict)
        print(status)

        p = Payment.objects.get(order_id=response['razorpay_order_id'])
        p.razorpay_payment_id = response['razorpay_payment_id']
        p.paid = True
        p.save()

        o = Order_details.objects.filter(order_id=response['razorpay_order_id'])
        print(o)
        for i in o:
            i.payment_status = "completed"
            i.save()

            u=User.objects.get(username=u)
            c=Cart.objects.filter(user=u)
            c.delete()
    except:
        pass

  return render(request,'payment_status.html',{'status':status})

@login_required()
def order_view(request):
    u=request.user
    o=Order_details.objects.filter(user=u)
    context={'orders':o}
    return render(request,'orderview.html',context)

@login_required()
def add_categories(request):
    if(request.method=="POST"):
        n=request.POST['n']
        d=request.POST['d']
        i=request.FILES['i']
        c=Categories.objects.create(name=n,description=d,image=i)
        c.save()
        return redirect('shop:categories')
    return render(request,'addcategories.html',)

@login_required()
def add_products(request):
    if (request.method == "POST"):
        n = request.POST['n']
        d = request.POST['d']
        i = request.FILES['i']
        p = request.POST['p']
        s = request.POST['s']
        c = request.POST['c']

        cat=Categories.objects.get(name=c)
        p = Product.objects.create(name=n,desc=d,image=i,price=p,stock=s,category=cat)
        p.save()
        return redirect('shop:categories')
    return render(request,'addproducts.html',)

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def search_products(request):
    p=None
    query=" "
    if(request.method=='POST'):
        query=request.POST['q']      #reads the query value
        print(query)
        if query:
            p=Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))  #filter the records matching with the query
    context={'pro':p,'query':query}
    return render(request,'search.html',context)

ecommerce/templates/addcategories.html
{% extends 'base.html' %}
{% load static%}
{% block content%}

<h2 class="text-center mt-4">Add Categories </h2>
<div class="container">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label  class="form-label">Name</label>
    <input type="text" class="form-control" name="n" placeholder="Category name">
  </div>
  <div class="mb-3">
    <label  class="form-label">Description</label>
    <input type="text" class="form-control" name="d" placeholder="write a desc">
  </div>
  <div class="mb-3">
    <label for="formFile" class="form-label">Image</label>
    <input class="form-control" type="file" name="i" id="formFile">
  </div>
     <div class="mb-3">
       <input type="submit" class="form-control">
     </div>
</form>
</div>

{% endblock %}

ecommerce/templates/addproducts.html
{% extends 'base.html' %}
{% load static%}
{% block content%}

<h2 class="text-center mt-4">Add Products </h2>
<div class="container">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label  class="form-label">Name</label>
    <input type="text" class="form-control" name="n" placeholder="category name">
  </div>
  <div class="mb-3">
    <label  class="form-label">Description</label>
    <input type="text" class="form-control" name="d" placeholder="description">
  </div>
  <div class="mb-3">
  <label for="formFile" class="form-label">Image</label>
  <input class="form-control" type="file" name="i" id="formFile">
</div>
     <div class="mb-3">
    <label  class="form-label">Price</label>
    <input type="number" class="form-control" name="p" placeholder="price">
  </div>
      <div class="mb-3">
    <label  class="form-label">Stock</label>
    <input type="number" class="form-control" name="s" placeholder="stock">
  </div>

    <div>
    <select name="c">
  <option selected>Categories</option>
 	{% for i in links %}
        <option value="{{i.name}}">{{i.name}}</option>
        {% endfor %}
</select>
    </div>


     <div class="mb-3">
       <input type="submit" class="form-control">
     </div>

</form>
</div>

{% endblock %}

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static%}
{% block content%}
<br>
<br>
<br>
<br>
<br>
<h3 class="text-center">SHOPPING CART</h3>
 <div class="container mt-5 p-3" style="margin-bottom:100px;">
   <div class="row">
     <div class="col-7">
       <table class="table table-bordered">

       <tr><th colspan="5">CART ITEMS</th></tr>
         {% for i in cart %}
         <tr>
           <td class="p-3"> <img src="{{i.product.image.url}}" height="150px" width="150px"></td>
           <td class="p-3">Product:{{i.product.name}}</td>
           <td class="p-3">Quantity:{{i.quality}}<br>
           UnitPrice{{i.product.price}}</td>
           <td>Subtotal:{{i.subtotal}}</td>
           <td>
             {% if i.product.stock > 0 %}<a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa fa-plus-circle text-dark" aria-hidden="true"></i></a>
                 <a href="{% url 'cart:cartremove' i.product.id %}"> <i class="fa fa-minus-circle text-dark" aria-hidden="true"></i></a>
                 <a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa fa-trash text-dark" aria-hidden="true"></i></a></td>
            {% else %}
               <a href="{% url 'cart:cartremove' i.product.id %}"> <i class="fa fa-minus-circle text-dark" aria-hidden="true"></i></a>
               <a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa fa-trash text-dark" aria-hidden="true"></i></a>
           {% endif %}
           </td>
         </tr>
         {% endfor %}
       </table>
       </div>

     <div class="col-4">
       <table class="table table-bordered">


         <tr><th colspan="4">CHECK OUT</th></tr>
           <tr><td>Total:{{total}}</td></tr>
       </table>
       <div class="d-flex justify-content-between">
           <a href="{% url 'cart:orderform' %}" class="btn btn-outline-info">Place Order</a>
             <a href="" class="btn btn-outline-info">Continue Shopping</a>

       </div>

   </div>


 </div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{product.image.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{product.name}}</h5>
        <p class="card-text">{{product.desc}}</p>
        <p class="card-text">{{product.price}}</p>
        <p class="card-text">{{product.stock}}</p>
        {% if user.is_superuser == True %}
          {% if product.stock > 0 %}
        <h4>Product In stock</h4>
        <a href="{% url 'shop:stock' product.id %}" class="btn btn-secondary fw-bold mt-3 mb-2 text-center">Add Stock</a>
        {% else %}
          <h4>Product Out Off Stock </h4>
        <a href="{% url 'shop:stock' product.id %}" class="btn btn-secondary fw-bold mt-3 mb-2 text-center">Add Stock</a>
        {% endif %}

        {% else %}
        {% if product.stock > 0 %}
         <a href="{% url 'cart:addtocart' product.id %}"  class="btn btn-outline-primary">Add to cart</a>
        {% else %}
        <h4>Out Of Stock</h4>
        {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static%}
{% block content%}

<h2 class="text-center mt-4">Login </h2>
<div class="container">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="username">
  </div>
  <div class="mb-3">
    <label  class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="password">
  </div>

     <div class="mb-3">
       <input type="submit" class="form-control">
     </div>
</div>
</form>


{% endblock %}

</body>
</html>

ecommerce/templates/logout.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static%}
{% block content%}
<br>
<h2>home page</h2>
<br>

{% endblock %}

</body>
</html>

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static%}
{% block content%}

<h2 class="text-center mt-4">Booking</h2>
<div class="container">
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3">
    <label  class="form-label">Address</label>
    <input type="text" class="form-control" name="a" placeholder="address">
  </div>
  <div class="mb-3">
    <label  class="form-label">Phone</label>
    <input type="number" class="form-control" name="p" placeholder="phone">
  </div>
    <div class="mb-3">
    <label  class="form-label">Pin</label>
    <input type="number" class="form-control" name="pi" placeholder="pin">
  </div>

     <div class="mb-3">
       <input type="submit" class="form-control">
     </div>

</form>
</div>

{% endblock %}

</body>
</html>

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static%}
{% block content%}

<div class="container mt-4 p-5 style=margin-bottom:100px;">
    <h3>Order Details</h3>
    {% for i in orders %}
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{i.products.image.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Product Name:{{i.products.name}}</h5>
        <p class="card-text">Price:{{i.products.price}}</p>
        <p class="card-text">Quantity:{{i.no_of_items}}</p>
        <p class="card-text">Ordered on:{{i.ordered_date}}</p>
        <p class="card-text">Order id:{{i.order_id}}</p>
        <p class="card-text">Delivery status:{{i.products.delivery_status}}</p>

      </div>
    </div>
  </div>
</div>
{% endfor %}
</div>
{% endblock %}

ecommerce/templates/payment.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static%}
{% block content%}
<br>
<br>

<form action="http://127.0.0.1:8000/cart/status/{{payment.name}}" class="fs-4 text-center p-5" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_37h3t9ZIGC5fDa"// Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Fashion.com"
    data-description="Shop Here"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
{% endblock %}

ecommerce/templates/payment_status.html
{% extends 'base.html' %}
{% load static%}
{% block content%}


{% if status  == True %}
    <h2>payment successful</h2>
{% else %}
    <h3>payment failed! </h3>
{% endif %}
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<img src="{{cat.image.url}}"  class="rounded mx-auto d-block"  height="80%" >

<div class="container mt-3">
    <h3 class="text-center">{{cat.name}}</h3>
    <p style="text-align:center;font-size:smaller">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>
</div>


<div class="row">
    {% for i in pro %}
                <div class="col-lg-6 col-md-3 col-sm-6">
                    <div class="blog__item">
                        <div class="blog__item__text">
                                <h4>{{i.name}}</h4>
                            <img  src="{{i.image.url}}" height="250px" width="50%">
<!--                            <h5 class="mt-4 text-center">{{i.description}}</h5>-->
                            <h5>{{i.price}}</h5>
                            <a href="{% url 'shop:details' i.id %}">Detail</a>
                        </div>
                        </div>
                    </div>
    {% endfor %}
</div>

<!--<h2 class="text-center mt-3">{{cat.name}}</h2>-->
<!--<h3 class="mt-4 text-center">{{cat.description}}</h3>-->

<!--<div class="row">-->
<!--    {% for i in pro %}-->
<!--                <div class="col-lg-4 col-md-6 col-sm-3 mx-auto" style="width: 200px;">-->
<!--                    <div class="blog__item">-->
<!--                        <div class="blog__item__pic set-bg" data-setbg="img/blog/blog-1.jpg"></div>-->
<!--                        <div class="blog__item__text">-->
<!--                                <h4>{{i.name}}</h4>-->
<!--                            <img class="img-fluid" src="{{i.image.url}}" height="150px" width="90%">-->
<!--                            <h5>{{i.price}}</h5>-->

<!--                            <a href="{% url 'shop:details' i.id %}">Details</a>-->
<!--                        </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--    {% endfor %}-->
<!--</div>-->


{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static%}
{% block content%}

<h2 class="text-center mt-4"> User Register </h2>
<div class="container">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="username">
  </div>
      <div class="mb-3">
    <label  class="form-label">Password</label>
    <input type="text" class="form-control" name="p" placeholder="password">
  </div>
    <div class="mb-3">
    <label  class="form-label">ConfirmPassword</label>
    <input type="text" class="form-control" name="cp" placeholder="confrimpassword">
  </div>

      <div class="mb-3">
    <label  class="form-label">First name</label>
    <input type="text" class="form-control" name= "f" placeholder="firstname">
  </div>
      <div class="mb-3">
    <label  class="form-label">Last name</label>
    <input type="text" class="form-control" name="l" placeholder="lastname">
  </div>
      <div class="mb-3">
    <label  class="form-label">Email</label>
    <input type="text" class="form-control" name="e" placeholder="email">
  </div>



     <div class="mb-3">
       <input type="submit" class="form-control">
     </div>
</form>
</div>

{% endblock %}

</body>
</html>

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" action="{% url 'search:search' %}">
    {% csrf_token %}
    <input class=" mb-3 mx-4 me-2 border border-dark" type="text" name="q" placeholder="Search...">
    <button type="submit">Search</button>
</form>


<div class="container mt-5">

    <h2>you have searched for {{query}}</h2>

<div class="row">
			{% for i in pro %}
					<div class="col-12 col-sm-6 col-md-4 mb-4 mb-md-5 mx-auto">

						<div class="post-entry">
							<a href="{% url 'shop:details' i.id %}" class="post-thumbnail"><img src="{{i.image.url}}"  alt="Image"  class="img-fluid"></a>
							<div class="name">
								<h2>{{i.name}}</h2>
							  <div class="post-content-entry"><b><i>
								  {{i.price}} </i></b><br>

                                             <a href="{% url 'shop:details' i.id %}" class="btn btn-primary">VIEW PRODUCT</a>

							  </div>
							</div>
						</div>
					</div>
						{% empty %}
    <h3 class="text-center">no result found</h3>
    {% endfor %}
</div>

{% endblock %}

ecommerce/templates/stock.html
{% extends 'base.html' %}
{% load static%}
{% block content%}

<h4 class="text-center mt-4">Add Stock </h4>
<div class="container">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

  <div class="mb-3">
    <label  class="form-label"></label>
    <input type="number" class="form-control" name="s" value="{{pro.stock}}" placeholder="stock">
  </div>

     <div class="mb-3">
       <input type="submit" class="form-control">
     </div>
</form>
</div>

{% endblock %}